### ISSUE TITLE
The `Main` file is not a valid javascript file.

### ISSUE THREAD

**Issue by andela-ioraelosi** [CammyTetehJr/number-reverse.js#1]
Great work with the "reverse number" function. There's one issue though:

The `Main` file is not a valid javascript file. Javascript files usually have a `.js` extension. I would appreciate it if you could convert this file.

**Comment by CammyTetehJr** [comment]
Thanks for the correction.

```
 On Friday, August 7, 2015 9:10 PM, Ifeanyi Oraelosi <notifications@github.com> wrote:
```

 Great work with the "reverse number" function. There's one issue though:The Main file is not a valid javascript file. Javascript files usually have a .js extension. I would appreciate it if you could convert this file.—

**Comment by andela-ioraelosi** [comment]
Nice work!
